id: P009507
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:33:40.226093
source_metadata:
  id: bdr:W1KG9749
  title: ཆོས་སྐྱོང་བའི་རྒྱལ་པོ་སྲོང་བཙན་སྒམ་པོའི་ཞལ་གདམས།
  author: ''
  volumes:
    753b98b568434102acffe6d952c1328c:
      image_group_id: I1KG9760
      title: ''
      volume_number: 1
      total_pages: 453
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
