id: I3BB08508
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:12:31+00:00'
last_modified: '2022-06-08T11:31:22.277251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9749
  title: ཆོས་སྐྱོང་བའི་རྒྱལ་པོ་སྲོང་བཙན་སྒམ་པོའི་ཞལ་གདམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8866':
      image_group_id: I1KG9760
      title: ''
      total_pages: 453
      order: 1
      base_file: 8866.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
